language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run
  - vendor/bin/phpunit -c module/Client/tests/phpunit.xml --coverage-php build/coverage/coverage-{/.}.cov {};

after_script:
   # Merges the individual clover reports of each component into a single clover.xml
  - php vendor/bin/phpcov.php --merge --clover build/logs/clover.xml --whitelist library build/coverage
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
